# https://taskfile.dev

version: '3'

includes:
  procedures:
    taskfile: ./procedures/Taskfile.yml

tasks:
  update:
    dir: ~/__WORKSHOP/devarmory/appimage-store
    cmds:
      - git fetch
      - git pull
      - npm install
      #- npm run sync-list
      #- npm run appindex-download
    silent: false
  default:
    cmds:
      - git status -s
      - echo "---"
      - echo "# APPIMAGES "
      - echo "> in total = $(ls ./*.AppImage | wc -l)"
      - ls *.AppImage -1 | grep ".AppImage"
    silent: true
